name: Go

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  glint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Install linter
        run: go install github.com/go-glint/glint/cmd/glint@latest
      - name: Lint
        run: glint ./...
